[tool.pydoctor]
project-name = "object-detection"
project-version = "0.1.0"
project-url = "https://qlllllll.github.io/fire-risk-object-detection"
html-viewsource = "https://github.com/qlllllll/fire-risk-object-detection/tree/main"
make-html = true
html-output = "docs/api"
project-base-dir = "."
docformat = "epytext"
intersphinx = "https://docs.python.org/3/objects.inv"
privacy = ['HIDDEN:src.geo_utils.GOOGLE_MAPS_API_KEY', 
  'HIDDEN:src.geo_utils.PARCEL_URL', 
  'HIDDEN:src.geo_utils.join_parcels', 
  'HIDDEN:src.geo_utils.new_pos', 
  'HIDDEN:src.geo_utils.round5', 
  'HIDDEN:src.object_detection_utils.DEVICE', 
  'HIDDEN:src.object_detection_utils.suppress_output', 
  'HIDDEN:src.object_detection_utils.new_position', 
  'HIDDEN:src.object_detection_utils.estimate_geolocations', 
  'HIDDEN:src.object_detection_utils.generate_box_corners', 
  'HIDDEN:src.object_detection_utils.mask_to_polygon',
  'HIDDEN:src.object_detection_utils.polygon_to_mask',
  'HIDDEN:src.object_detection_utils.refine_masks',
  'HIDDEN:src.object_detection_utils.polygon_to_mask',
  'HIDDEN:src.plot_utils.random_named_css_colors'
  ]
