[tool.pydoctor]
project-name = "object-detection"
project-version = "0.1.0"
project-url = "https://qlllllll.github.io/fire-risk-object-detection"
html-viewsource = "https://github.com/qlllllll/fire-risk-object-detection/tree/main"
make-html = true
html-output = "docs/api"
project-base-dir = "."
docformat = "epytext"
intersphinx = "https://docs.python.org/3/objects.inv"
