title: Wildfire Prevention
description: ""
theme: just-the-docs

url: https://qlllllll.github.io/wildfire-prevention

aux_links:
  GitHub: https://github.com/qlllllll/wildfire-prevention

nav_external_links:
  - title: API
    url: ./api
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false